#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /config/.config/Subtitle\ Edit
mkdir -p /root/.config

ln -s /config/.config/Subtitle\ Edit /root/.config/Subtitle\ Edit

lsiown -R abc:abc \
    /root/.config/Subtitle\ Edit \
    /config \
    /opt/subtitleedit